sources:
  - name: lakehouse_raw
    loader: duckdb

    tables:
      - name: raw_biometric_events
        config:
          external_location: "s3://warehouse/db/raw_biometric_events/data/**/*.parquet"

      - name: user_profiles
        config:
          external_location: "s3://warehouse/db/user_profiles/data/*.parquet"

      - name: music_tracks
        config:
          external_location: "s3://warehouse/db/music_tracks/data/*.parquet"