dbt_lakehouse:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      extensions:
        - httpfs
        - parquet

      settings:
        s3_endpoint: '{{ env_var("MINIO_ENDPOINT") }}'
        s3_access_key_id: '{{ env_var("MINIO_USER") }}'
        s3_secret_access_key: '{{ env_var("MINIO_PASS") }}'
        s3_url_style: 'path'
        s3_use_ssl: false

        max_memory: '2GB'
        threads: 2

  target: dev