name: 'dbt_lakehouse'
version: '1.0.0'

profile: 'dbt_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_lakehouse:
    +materialized: table
    +file_format: parquet

    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts